### ISSUE TITLE
create instance_start, instance_end for single events

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/uiowa_events#115]
Should this just be the first/last dates? Or should we calculate the next upcoming instance and filter out past ones?

**Comment by genjohnson** [comment]
For a series of event instances that occur close together (e.g., the same event happens every day for a week), I think it would be helpful to have `instance_start` be the start date of the very first instance and `instance_end` the end date of the final instance. This way, if someone wanted to display just one node/object for the whole series they would have easy access to the date range of the series. 

For a series of event instances that are far apart (e.g., the same event happens once a month), sites would still have the option to display each instance as a separate node/object so that their event list isn't cluttered with this one long-running series at the top of the list all the time.

**Comment by adamdelaney** [comment]
After a brief requirement we have decided that a single event listing will show the next upcoming if applicable with a drop down to show all of the event instance dates. If the date is in the past it will show all of the dates.

**Comment by richardbporter** [comment]
@genjohnson This only applies to the single display of an event, e.g. mysite.com/event/123.

**Comment by richardbporter** [comment]
Related #119
