### ISSUE TITLE
Change teaser truncate to description_text value and output description_text to teaser template

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/uiowa_events#89]
[With the addition of truncate on descriptions (html markup)](https://github.com/ITS-UofIowa/uiowa_events/blob/7.x-1.x/includes/uiowa_events.teaser.inc#L39), there is the possibility of breaking a tag without proper closure.

truncate is valuable for teasers, but should be used on the description_text value instead and that value should be placed within the teaser display.

**Comment by adamdelaney** [comment]
Looks like text_summary() may be a better option to preserve text formatting: https://api.drupal.org/api/drupal/modules%21field%21modules%21text%21text.module/function/text_summary/7.x

**Comment by genjohnson** [comment]
@adamdelaney Joe, Rick and I discussed whether text formatting should be preserved in the teaser, and the consensus was that formatting in the teaser is not generally expected (which is why this was opened to use description_text).

However, I don't have strong feelings on this. If others support that we should allow formatting in the teaser display, that's fine with me.

**Comment by richardbporter** [comment]
This issue was resolved with #90. I think sites that want formatting in the teaser could preprocess or override the teaser theme implementation.

**Comment by richardbporter** [comment]
Sorry - I just re-implemented this the 7.x-2.x branch with bdfee22.
